http:
  routers:
    organization-private:
      rule: "PathPrefix(`/organization/v1/private`)"
      service: organization
      entryPoints:
        - web
      middlewares:
        - stripprefix-organization
        - cors-headers
        - jwt-auth

    organization-public:
      rule: "PathPrefix(`/organization/v1/public`) || PathPrefix(`/organization/docs`)"
      service: organization
      entryPoints:
        - web
      middlewares:
        - stripprefix-organization
        - cors-headers

  services:
    organization:
      loadBalancer:
        servers:
          - url: "http://organization-service:3102"

  middlewares:
    stripprefix-organization:
      stripPrefix:
        prefixes:
          - "/organization"
    jwt-auth:
      forwardAuth:
        address: "http://identity-service:3101/v1/public/auth/validate"
        authResponseHeaders:
          - "x-user"
    cors-headers:
      headers:
        accessControlAllowOriginList:
          - "http://localhost:3000"
        accessControlAllowMethods: "GET, PUT, POST, DELETE, OPTIONS"
        accessControlAllowHeaders: "*"
        accessControlMaxAge: "86400"