services:
  db:
    image: postgres
    env_file:
      - .env
    container_name: postgres-db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - /var/lib/redis
    networks:
      - backend
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    build:
      context: .
      dockerfile: tooling/rabbitmq/Dockerfile
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "3100:3100"
      - "8080:8080"
    networks:
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./tooling/traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./tooling/traefik:/etc/traefik/traefik_dynamic"
  identity-service:
    container_name: identity-service
    build:
      context: .
      dockerfile: apps/identity-service/Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
      - ${IDENTITY_ENV}
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: apps/notification-service/Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
      - ${NOTIFICATIONS_ENV}
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  backend:
    driver: bridge